# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddae0a9600e61718b139ce3014310438f0b9276241bd30e5ff428f514015c52fe8d1808e1f4adb82741d4f86ea3f4b4bcbfba91b46c6a96b0ae7d7bee8227fc7

test:
  secret_key_base: 456d4fdd89ac7131547a85d6b743f7cafb59576488fbb41f8dbfdcf93824915d59c07f1ae567a6e45e780d5e63cb88d6b361d60145cfecded070a6843c20f5cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
